# Generated by Django 3.2.7 on 2021-10-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0002_auto_20211005_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reg_deadline',
            field=models.DateField(null=True, verbose_name='Registration Deadline'),
        ),
    ]
