# Generated by Django 3.2.7 on 2021-10-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0003_auto_20211005_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='series',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='series',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='series',
            name='winner',
        ),
        migrations.DeleteModel(
            name='Matches',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
