# Generated by Django 3.2.7 on 2021-10-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0005_fixture_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipate',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='DOTA2_APP.fixture'),
        ),
    ]
