# Generated by Django 3.2.7 on 2021-10-23 05:43

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0009_auto_20211005_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='body',
            field=django_editorjs.fields.EditorJsField(default=''),
            preserve_default=False,
        ),
    ]
