# Generated by Django 3.2.7 on 2021-10-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0010_tournament_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='body',
        ),
    ]
