# Generated by Django 3.2.7 on 2021-10-23 08:15

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0011_remove_tournament_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='content',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
