# Generated by Django 3.2.7 on 2021-10-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0013_remove_tournament_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
