# Generated by Django 3.2.7 on 2021-10-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0014_auto_20211025_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='estimated_mmr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
