# Generated by Django 3.2.7 on 2021-10-25 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DOTA2_APP', '0016_tournamentparticipate_text_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
