# Generated by Django 3.2.7 on 2021-10-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0017_tournamentparticipate_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentparticipate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.profile'),
        ),
    ]
