# Generated by Django 3.2.7 on 2021-10-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0026_test2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
