# Generated by Django 3.2.7 on 2021-10-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0028_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='originalUpload',
        ),
    ]
