# Generated by Django 3.2.7 on 2021-10-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0029_remove_team_originalupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='team/logo/default.png', upload_to=''),
        ),
    ]
