# Generated by Django 3.2.7 on 2021-11-05 13:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0034_team_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_Instruction', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('payment_method_used', models.CharField(blank=True, choices=[('BKash', 'BKash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad')], default='BKash', max_length=50, null=True)),
                ('entry_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_with_mobileNo', models.CharField(blank=True, max_length=11, null=True)),
                ('Transection_Id', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.tournament')),
            ],
        ),
    ]
