# Generated by Django 3.2.7 on 2021-11-05 14:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0035_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='payment_Info',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
