# Generated by Django 3.2.7 on 2021-11-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0037_alter_tournament_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sumbitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.profile'),
        ),
    ]
