# Generated by Django 3.2.7 on 2021-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0039_remove_payment_payment_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='form_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
