# Generated by Django 3.2.7 on 2021-11-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0040_payment_form_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.tournamentparticipate'),
        ),
    ]
