# Generated by Django 3.2.7 on 2021-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0041_alter_payment_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tranx_success',
            field=models.BooleanField(default=False),
        ),
    ]
