# Generated by Django 3.2.7 on 2021-11-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0043_auto_20211106_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStageMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Match Date')),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BYE', 'BYE'), ('Not Scheduled', 'Not Scheduled'), ('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='Not Scheduled', max_length=30)),
                ('team_1_score', models.PositiveIntegerField(blank=True, null=True)),
                ('team_2_score', models.PositiveIntegerField(blank=True, null=True)),
                ('team_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_matches_groupstage', to='DOTA2_APP.tournamentparticipate')),
                ('team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_matches_groupstage', to='DOTA2_APP.tournamentparticipate')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won_groupStage', to='DOTA2_APP.tournamentparticipate')),
            ],
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.groupstagematch'),
        ),
    ]
