# Generated by Django 3.2.7 on 2021-11-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0044_auto_20211106_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstagematch',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='groupstagematch',
            name='team_2',
        ),
        migrations.RemoveField(
            model_name='groupstagematch',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='stage',
        ),
        migrations.AlterField(
            model_name='match',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='DOTA2_APP.fixture'),
        ),
        migrations.DeleteModel(
            name='GroupStage',
        ),
        migrations.DeleteModel(
            name='GroupStageMatch',
        ),
    ]
