# Generated by Django 3.2.7 on 2021-11-09 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0045_auto_20211109_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('group', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (3, 3)])),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date GroupStage')),
                ('matches_per_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rounds', models.IntegerField(default=0)),
                ('current_round', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.tournament')),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Matche'},
        ),
        migrations.CreateModel(
            name='GroupStageMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Match Date')),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('match_round', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BYE', 'BYE'), ('Not Scheduled', 'Not Scheduled'), ('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='Not Scheduled', max_length=30)),
                ('player_1_score', models.PositiveIntegerField(blank=True, null=True)),
                ('player_2_score', models.PositiveIntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupstage_matches', to='DOTA2_APP.groupstage')),
                ('team_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_groupStage', to='DOTA2_APP.tournamentparticipate')),
                ('team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_groupStage', to='DOTA2_APP.tournamentparticipate')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won_groupStage', to='DOTA2_APP.tournamentparticipate')),
            ],
            options={
                'verbose_name': 'Group Stage Matche',
            },
        ),
    ]
