# Generated by Django 3.2.7 on 2021-11-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0046_auto_20211109_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStagePointTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Group Stage Point Table',
            },
        ),
        migrations.RenameField(
            model_name='groupstagematch',
            old_name='player_1_score',
            new_name='team_1_score',
        ),
        migrations.RenameField(
            model_name='groupstagematch',
            old_name='player_2_score',
            new_name='team_2_score',
        ),
        migrations.AlterField(
            model_name='groupstagematch',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='Not Scheduled', max_length=30),
        ),
    ]
