# Generated by Django 3.2.7 on 2021-11-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0047_auto_20211109_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstage',
            name='group_champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.team'),
        ),
        migrations.AddField(
            model_name='groupstagepointtable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupstage_PointsTable', to='DOTA2_APP.groupstage'),
        ),
        migrations.AddField(
            model_name='groupstagepointtable',
            name='loss',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='groupstagepointtable',
            name='played',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='groupstagepointtable',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='groupstagepointtable',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.tournamentparticipate'),
        ),
        migrations.AddField(
            model_name='groupstagepointtable',
            name='win',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
