# Generated by Django 3.2.7 on 2021-11-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0048_auto_20211109_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstagepointtable',
            name='matches',
            field=models.ManyToManyField(blank=True, to='DOTA2_APP.GroupStageMatch'),
        ),
    ]
