# Generated by Django 3.2.7 on 2021-11-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0049_groupstagepointtable_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstage',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
