# Generated by Django 3.2.7 on 2021-11-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0050_alter_groupstage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstage',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='groupstage',
            name='rounds',
        ),
    ]
