# Generated by Django 3.2.7 on 2021-11-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0051_auto_20211109_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstagepointtable',
            name='qualified_status',
            field=models.BooleanField(default=False),
        ),
    ]
