# Generated by Django 3.2.7 on 2021-11-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0052_groupstagepointtable_qualified_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstagematch',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOTA2_APP.tournament'),
        ),
        migrations.AlterField(
            model_name='groupstage',
            name='group',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
