# Generated by Django 3.2.7 on 2021-11-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0053_auto_20211109_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstagematch',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='groupstagematch',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Match Time'),
        ),
        migrations.AlterField(
            model_name='groupstagematch',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Match Date'),
        ),
    ]
