# Generated by Django 3.2.7 on 2021-11-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0054_auto_20211111_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstagematch',
            name='date',
        ),
    ]
