# Generated by Django 3.2.7 on 2021-11-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0055_remove_groupstagematch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstagematch',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Match Date'),
        ),
    ]
