# Generated by Django 3.2.7 on 2021-11-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0056_groupstagematch_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Matches'},
        ),
        migrations.AddField(
            model_name='groupstage',
            name='total_rounds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
