# Generated by Django 3.2.7 on 2021-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0057_auto_20211111_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstagematch',
            name='team_1_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='groupstagematch',
            name='team_2_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
