# Generated by Django 3.2.7 on 2021-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0058_auto_20211111_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstagematch',
            name='team_1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupstagematch',
            name='team_2_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
