# Generated by Django 3.2.7 on 2021-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0059_auto_20211111_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstagematch',
            name='status',
            field=models.CharField(blank=True, choices=[('TBD', 'TBD'), ('Not Scheduled', 'Not Scheduled'), ('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='Not Scheduled', max_length=30, null=True),
        ),
    ]
