# Generated by Django 3.2.7 on 2021-11-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTA2_APP', '0060_alter_groupstagematch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstagematch',
            name='status',
            field=models.CharField(blank=True, choices=[('TBD', 'TBD'), ('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='TBD', max_length=30, null=True),
        ),
    ]
